#!/bin/bash
if [ -z "$1" ]; then
  echo "Usage: <version, no prefix>"
  exit 1
fi

set -ex

version="$1"
branch="release-$version"
tag="v$version"
LICENSE=LICENSE.md
VERSION=version.json

git checkout -b "$branch" master
sed --in-place "s/Development Draft/$version/" $LICENSE
echo "\"$version\"" > $VERSION
git add $LICENSE $VERSION
git commit -m "Version $version"
git tag "$tag"
git push origin "$branch"
git push origin "$tag"
git checkout master
